const ACCOUNT_LOCKED = 1001;

const EMAIL_ALREADY_EXIST = 2001;
const USERNAME_ALREADY_EXIST = 2002;

const INVALID_SCHEMA = 3001;
const INVALID_USER = 3002;
const INVALID_TOKEN = 3003;
const INVALID_FILE = 3004;
const INVALID_TENOR = 3005;
const INVALID_INSTALLMENT = 3006;
const INVALID_INTEREST = 3007;
const INVALID_LOAN = 3008;
const INVALID_NOTIF = 3009;
const INVALID_SUBM = 3010;
const INVALID_PRODUCT_TYPE = 3011;
const INVALID_CONSUMED_PRODUCT = 3012;
const INVALID_ROLE = 3013;

const NOT_ADMIN = 4001;
const NOT_FOUND = 4002;

const RESOURCE_FORBIDDEN = 5001;
const RESOURCE_NOT_FOUND = 5002;

const PASSWORD_NOT_MATCH = 6001;

export default {
  ACCOUNT_LOCKED,
  EMAIL_ALREADY_EXIST,
  USERNAME_ALREADY_EXIST,
  INVALID_SCHEMA,
  INVALID_USER,
  INVALID_TOKEN,
  INVALID_FILE,
  INVALID_TENOR,
  INVALID_INSTALLMENT,
  INVALID_INTEREST,
  INVALID_LOAN,
  INVALID_NOTIF,
  INVALID_SUBM,
  INVALID_PRODUCT_TYPE,
  INVALID_CONSUMED_PRODUCT,
  INVALID_ROLE,
  NOT_ADMIN,
  NOT_FOUND,
  RESOURCE_FORBIDDEN,
  RESOURCE_NOT_FOUND,
  PASSWORD_NOT_MATCH,
};
