const ACCOUNT_LOCKED = 7523;

const EMAIL_ALREADY_EXIST = 3355;
const USERNAME_ALREADY_EXIST = 4554;

const INVALID_SCHEMA = 2386;
const INVALID_USER = 7845;

export default {
  ACCOUNT_LOCKED,
  EMAIL_ALREADY_EXIST,
  USERNAME_ALREADY_EXIST,
  INVALID_SCHEMA,
  INVALID_USER,
};
