const ACCOUNT_LOCKED = 1001;

const EMAIL_ALREADY_EXIST = 2001;
const USERNAME_ALREADY_EXIST = 2002;

const INVALID_SCHEMA = 3001;
const INVALID_USER = 3002;
const INVALID_TOKEN = 3003;
const INVALID_FILE = 3004;

const NOT_ADMIN = 4001;

export default {
  ACCOUNT_LOCKED,
  EMAIL_ALREADY_EXIST,
  USERNAME_ALREADY_EXIST,
  INVALID_SCHEMA,
  INVALID_USER,
  INVALID_TOKEN,
  INVALID_FILE,
  NOT_ADMIN,
};
